# Generated by Django 6.0.2 on 2026-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedcommenter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
