# Generated by Django 6.0.2 on 2026-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
