# Generated by Django 6.0.2 on 2026-03-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_category_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(
                default="This is default description", max_length=250
            ),
            preserve_default=False,
        ),
    ]
